---
- name: Install apcupsd
  package:
    name: apcupsd
- name: Configure apcupsd.conf
  copy:
    src: apcupsd.conf
    dest: /etc/apcupsd/apcupsd.conf
    backup: yes
- name: Start and enable apcupsd
  service:
    name: apcupsd
    state: started
    enabled: yes
